AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 graviton migration workshop'

Parameters:
  # AWS SSM Parameter Store를 통해 최신 AL2023 AMI ID 자동 획득
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
    Description: "Automatically fetches the latest Amazon Linux 2023 AMI ID"

  KeyName:
    Description: "Name of an existing EC2 KeyPair to enable SSH access"
    Type: AWS::EC2::KeyPair::KeyName

  UserDataScript:
    Type: String
    Description: "Content of monte-carlo.sh"

  MyIP:
    Type: String
    Description: "My Public IP address (x.x.x.x/32)"

Resources:
  # 1. 네트워크 구성
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: [{ Key: Name, Value: "graviton-mig" }]

  # --- [신규 추가] Bastion용 IAM 설정 ---
  BastionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationDescribePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # 1. CloudFormation & SSM & Describe (Read-only 공통)
              - Effect: Allow
                Action: 
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:DescribeStackResource"
                  - "ssm:GetParameters"
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeLaunchTemplates"
                  - "autoscaling:DescribeAutoScalingGroups"
                  - "autoscaling:DescribeInstanceRefreshes"
                Resource: "*"
              # 2. EC2 인스턴스 제어
              - Effect: Allow
                Action: 
                  - 'ec2:RunInstances'
                  - 'ec2:CreateTags'
                  - "ec2:TerminateInstances"
                  - "ec2:DescribeVpcs",
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeSecurityGroups"
                Resource: "*"
              # 3. ELB 타겟 그룹 제어
              - Effect: Allow
                Action:
                  - "elasticloadbalancing:DescribeTargetGroups"
                  - "elasticloadbalancing:DescribeTargetHealth"
                  - "elasticloadbalancing:RegisterTargets"
                  - "elasticloadbalancing:DeregisterTargets"
                  - "elasticloadbalancing:CreateTargetGroup"
                Resource: "*"    
              # 4. 런치 템플릿 버전 생성 (형식 수정됨)
              - Effect: "Allow"
                Action: 
                  - "ec2:CreateLaunchTemplate"
                  - "ec2:CreateLaunchTemplateVersion"
                Resource: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:launch-template/*"
              # 5. ASG 업데이트 및 인스턴스 새로 고침 (형식 수정됨)
              - Effect: "Allow"
                Action: 
                  - "autoscaling:UpdateAutoScalingGroup"
                  - "autoscaling:StartInstanceRefresh"
                Resource: !Sub "arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:*"

  BastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BastionRole  

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  NATEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATEIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true

  # 프라이빗 서브넷 (ASG 인스턴스용)
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.11.0/24
 
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.0.12.0/24

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PrivSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: { SubnetId: !Ref PrivateSubnet1, RouteTableId: !Ref PrivateRouteTable }
  
  PrivSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: { SubnetId: !Ref PrivateSubnet2, RouteTableId: !Ref PrivateRouteTable }

  # 3. 배스천 호스트 (Bastion Host)
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: m6i.4xlarge
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref BastionInstanceProfile
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds: [ !Ref EC2SG ]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo -u ec2-user -i <<'EC2_USER_SCRIPT'
          curl -fsSL https://code-server.dev/install.sh | sh && sudo systemctl enable --now code-server@ec2-user
          sleep 5
          sed -i 's/127.0.0.1/0.0.0.0/g; s/auth: password/auth: none/g' /home/ec2-user/.config/code-server/config.yaml
          EC2_USER_SCRIPT

          sudo systemctl restart code-server@ec2-user
      Tags: [{ Key: Name, Value: "vscode-web" }]

  # 2. 보안 그룹
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP from ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0           # 실제 환경에선 특정 IP로 제한 권장
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0           # 실제 환경에선 특정 IP로 제한 권장
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: !Ref MyIP           # [중요] 특정 IP만 웹 접속 허용  

  # 3. 로드 밸런서 (ALB)
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "my-alb"  
      Subnets: [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]
      SecurityGroups: [ !Ref ALBSG ]

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "tg-x86"  
      HealthCheckPath: /
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: instance
      # --- 여기서부터 헬스 체크 설정 ---
      HealthCheckProtocol: HTTP
      HealthCheckPort: "80"
      HealthCheckPath: /               # 검사 경로
      HealthCheckIntervalSeconds: 20   # 체크 주기 (초)
      HealthCheckTimeoutSeconds: 5     # 응답 대기 시간 (초)
      HealthyThresholdCount: 2         # 이 횟수만큼 성공하면 Healthy
      UnhealthyThresholdCount: 2       # 이 횟수만큼 실패하면 Unhealthy
      Matcher:
        HttpCode: 200                 # 성공으로 간주할 HTTP 코드

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  # 4. Auto Scaling 설정 (c6i.2xlarge)
  ASGLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: "asg-lt-x86"
      LaunchTemplateData:
        InstanceType: c6i.2xlarge
        ImageId: !Ref LatestAmiId
        KeyName: !Ref KeyName
        SecurityGroupIds: [ !Ref EC2SG ]
        UserData:
          Fn::Base64: !Ref UserDataScript
        MetadataOptions:                       # meta tag 활성화
          HttpEndpoint: enabled
          HttpTokens: required
          InstanceMetadataTags: enabled  
          
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: "asg-x86"
      VPCZoneIdentifier: [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]
      LaunchTemplate:
        LaunchTemplateId: !Ref ASGLaunchTemplate
        Version: !GetAtt ASGLaunchTemplate.LatestVersionNumber
      MinSize: '2'
      MaxSize: '4'
      DesiredCapacity: '2'
      TargetGroupARNs: [ !Ref ALBTargetGroup ]
      Tags:
        - Key: Name
          Value: "x86-nginx"  
          PropagateAtLaunch: true    

  # 5. 동적 스케일링 정책 (CPU 50%)
  CPUScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50.0

Outputs:
  ALBURL:
    Description: "Copy this URL to your browser to access the ALB"
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  ALBSecurityGroupId:
    Description: "The ID of the ALB Security Group"
    Value: !Ref ALBSG

  EC2SecurityGroupId:
    Description: "The ID of the EC2 Security Group"
    Value: !Ref EC2SG

  ALBName:
    Description: "The name of the Load Balancer"
    Value: !Ref ApplicationLoadBalancer

  TargetGroupName:
    Description: "The name of the x86 Target Group"
    Value: !GetAtt ALBTargetGroup.TargetGroupName

  LaunchTemplateName:
    Description: "The name of the Launch Template"
    Value: "asg-lt-x86"

  AutoScalingGroupName:
    Description: "The name of the Auto Scaling Group"
    Value: !Ref AutoScalingGroup

  BastionHostDNS:
    Description: "Public DNS name of the Bastion Host"
    Value: !GetAtt BastionHost.PublicDnsName 
  
  BastionHostIP:
    Description: "Public IP address of the Bastion Host"
    Value: !GetAtt BastionHost.PublicIp 
    
