AWSTemplateFormatVersion: '2010-09-09'
Description: 'ALB + ASG with Automatic AMI Discovery (c6i.2xlarge)'

Parameters:
  # AWS SSM Parameter Store를 통해 최신 AL2023 AMI ID 자동 획득
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
    Description: "Automatically fetches the latest Amazon Linux 2023 AMI ID"

  KeyName:
    Description: "Name of an existing EC2 KeyPair to enable SSH access"
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  # 1. 네트워크 구성
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: [{ Key: Name, Value: "Public-Service-VPC" }]

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true

  # 프라이빗 서브넷 (ASG 인스턴스용)
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.11.0/24
 
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.0.12.0/24

  # NAT Gateway (프라이빗 인스턴스의 업데이트 등을 위함)
  NATEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NATGateway:
    Type: AWS::EC2::NATGateway
    Properties:
      AllocationId: !GetAtt NATEIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PrivSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: { SubnetId: !Ref PrivateSubnet1, RouteTableId: !Ref PrivateRouteTable }
  
  PrivSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: { SubnetId: !Ref PrivateSubnet2, RouteTableId: !Ref PrivateRouteTable }

  # 3. 배스천 호스트 (Bastion Host)
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c7i.2xlarge
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds: [ !Ref EC2SG ]
      Tags: [{ Key: Name, Value: "vscode-web" }]

  # 2. 보안 그룹
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP from ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # 실제 환경에선 특정 IP로 제한 권장
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSG

  # 3. 로드 밸런서 (ALB)
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "my-alb"  
      Subnets: [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]
      SecurityGroups: [ !Ref ALBSG ]

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "tg-x86"  
      HealthCheckPath: /
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: instance

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  # 4. Auto Scaling 설정 (c6i.2xlarge)
  ASGLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: "asg-lt-x86"
      LaunchTemplateData:
        InstanceType: c6i.2xlarge
        ImageId: !Ref LatestAmiId
        KeyName: !Ref KeyName
        SecurityGroupIds: [ !Ref EC2SG ]
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            dnf update -y
            dnf install -y nginx
            
            # IMDSv2 토큰 가져오기 (메타데이터 접근용)
            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            
            # 인스턴스 정보 추출
            IP_PRIVATE=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/local-ipv4)
            INSTANCE_TYPE=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-type)
            INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-id)
            HOSTNAME=$(hostname)
            ARCH=$(uname -m)
            CPU_INFO=$(lscpu | grep "Model name" | cut -d':' -f2 | xargs)
            MEM_INFO=$(free -h | awk '/^Mem:/ {print $2}')

            # HTML 파일 생성
            cat <<EOF > /usr/share/nginx/html/index.html
            <html>
            <head><title>EC2 Status</title></head>
            <body>
              <h1>EC2 Instance Information</h1>
              <p><b>Instance Type:</b> $INSTANCE_TYPE</p>             
              <p><b>Instance Id:</b> $INSTANCE_ID</p>
              <p><b>Architecture:</b> $ARCH</p>
              <p><b>Private IP:</b> $IP_PRIVATE</p>
              <p><b>Hostname:</b> $HOSTNAME</p>
              <p><b>CPU:</b> $CPU_INFO</p>
              <p><b>Memory:</b> $MEM_INFO</p>
              <hr>
              <p>Generated at: $(date)</p>
            </body>
            </html>
            EOF

            systemctl start nginx
            systemctl enable nginx


  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: "asg-x86"
      VPCZoneIdentifier: [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]
      LaunchTemplate:
        LaunchTemplateId: !Ref ASGLaunchTemplate
        Version: !GetAtt ASGLaunchTemplate.LatestVersionNumber
      MinSize: '2'
      MaxSize: '4'
      DesiredCapacity: '2'
      TargetGroupARNs: [ !Ref ALBTargetGroup ]
      Tags:
        - Key: Name
          Value: "x86-nginx"  
          PropagateAtLaunch: true    

  # 5. 동적 스케일링 정책 (CPU 50%)
  CPUScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50.0

Outputs:
  ALBURL:
    Description: "Copy this URL to your browser to access the ALB"
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  ALBSecurityGroupId:
    Description: "The ID of the ALB Security Group"
    Value: !Ref ALBSG

  EC2SecurityGroupId:
    Description: "The ID of the EC2 Security Group"
    Value: !Ref EC2SG

  ALBName:
    Description: "The name of the Load Balancer"
    Value: !Ref ApplicationLoadBalancer

  TargetGroupName:
    Description: "The name of the x86 Target Group"
    Value: !GetAtt ALBTargetGroup.TargetGroupName

  LaunchTemplateName:
    Description: "The name of the Launch Template"
    Value: !Ref ASGLaunchTemplate

  AutoScalingGroupName:
    Description: "The name of the Auto Scaling Group"
    Value: !Ref AutoScalingGroup

  
    
